### ISSUE TITLE
A user attempts to change their password but encounters issues

### ISSUE THREAD

**Issue by Sharmakunjan** [Green-Haven-Hostel/Hostel-Management-System#4]
Verify Input: We'll first ensure that the new password meets any requirements 
Check Update Process: We'll review the code responsible for updating the password in the database to ensure it is functioning correctly.
Error Handling: If there are any error messages or feedback provided during the password change process, we'll review them to identify any specific issues.

**Comment by sugampathak11** [comment]
I'm pleased to inform you that the issue with changing your password has been resolved. After investigating the issue, we identified and fixed the root cause.
The problem was caused by a bug in the password update process . Once we corrected the code, you should now be able to change your password successfully.
